### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by dvandyk** [okkez/coveralls-lcov#13]
When running automated coverage tests via TravisCI, I encountered the following problem:
```
/var/lib/gems/2.3.0/gems/coveralls-lcov-1.5.1/lib/coveralls/lcov/runner.rb:75:in `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /var/lib/gems/2.3.0/gems/coveralls-lcov-1.5.1/lib/coveralls/lcov/runner.rb:75:in `to_json'
	from /var/lib/gems/2.3.0/gems/coveralls-lcov-1.5.1/lib/coveralls/lcov/runner.rb:75:in `run'
	from /var/lib/gems/2.3.0/gems/coveralls-lcov-1.5.1/bin/coveralls-lcov:5:in `<top (required)>'
	from /usr/local/bin/coveralls-lcov:23:in `load'
	from /usr/local/bin/coveralls-lcov:23:in `<main>'
```
I am a bit puzzled, since the problem occurred suddenly. The coveralls-lcov source coude leads me to believe that UTF-8 is the default source encoding. I checked using ```find```'s ```--mime``` option that
all my ```.cc``` and ```.hh``` files are either ```US-ASCII``` or ```utf-8``` encoded.

My setup can be viewed [here](https://github.com/eos/eos/blob/master/.travis/build-and-test.bash#L46).
I would welcome any hint toward what might be going wrong suddenly.

**Comment by dvandyk** [comment]
I solved the problem by forcing ```--source-encoding=ISO-8859-1``` on my end. Sorry for the confusion.
