### ISSUE TITLE
No such file or directory - developer1.cpp (Errno::ENOENT)

### ISSUE THREAD

**Issue by apolukhin** [okkez/coveralls-lcov#4]
Hi,

I've got the following error:
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:44:in `initialize': No such file or directory - /home/travis/build/apolukhin/Boost-Cookbook-4880OS/developer1.cpp (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:44:in `open'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:44:in `generate_source_file'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:14:in `block in convert'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:13:in `each'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/converter.rb:13:in `convert'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/lib/coveralls/lcov/runner.rb:59:in `run'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/coveralls-lcov-1.1.2/bin/coveralls-lcov:5:in `<top (required)>'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/coveralls-lcov:23:in `load'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/coveralls-lcov:23:in `<main>'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

I have no file `developer1.cpp` in project, so this seems strange. Here's the full build and test log from TravisCI: https://travis-ci.org/apolukhin/Boost-Cookbook-4880OS/builds/54086579

**Comment by okkez** [comment]
Check your lcov command result, please.
https://travis-ci.org/apolukhin/Boost-Cookbook-4880OS/builds/54086579#L3428

Lcov command cannot find some source files such as developer1.cpp.

**Comment by apolukhin** [comment]
Oh, thanks! That's my issue
